# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gimp-ScriptFu-Client
version:      1.01
version_from: lib/Gimp/ScriptFu/Client.pm
installdirs:  site
requires:
    Filter::Simple:                0
    Text::Template:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
